import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FavProvider } from "./context/fav";
import Navbar from "./navbar/page";
import { Toaster } from "react-hot-toast";
import { ShopingProvider } from "./context/shoping";
import Footer from "./footer/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body>

        <FavProvider> 
          <ShopingProvider>
            <Navbar />
              {children}
              <Toaster position="top-center" reverseOrder={false} />
              <Footer />
          </ShopingProvider>
        </FavProvider>
      </body>
    </html>
  );
}
