
export const allProducts = [
  { "id" : 1 , "name" : "Lovely pistachio Maske" , "price":80, "image" : "foto-1.jpg" }, 
  { "id" : 2 , "name" : "Vitamin C Maske" , "price":80, "image" : "foto-2.jpg" }, 
  { "id" : 3 , "name" : "ALOE  VERA  MASKE" , "price":80, "image" : "foto-3.jpg" }, 
  { "id" : 4 , "name" : " HoNIG MASKE " , "price":80, "image" : "foto-4.jpg" }, 
  { "id" : 5 , "name" : "TOTES MEER MASKE " , "price":80, "image" : "foto-5.jpg" },
  { "id" : 6 , "name" : "GLOW PEEL" , "price":80, "image" : "foto-6.jpg" },
  { "id" : 7 , "name" : "RETINOL MASKE" , "price":80, "image" : "foto-7.jpg" },
  { "id" : 8 , "name" : " FALTEN MASKE" , "price":80, "image" : "foto-8.jpg" },
  { "id" : 9 , "name" : "Creme - ölHANDLOTION" , "price":190, "image" : "foto-9.jpg" },
  { "id" : 10 , "name" : "GLamoIous Moment " , "price":190, "image" : "foto-10.jpg" },
  { "id" : 11 , "name" : "Schnell  einziehende " , "price":190, "image" : "foto-11.jpg" },
  { "id" : 12 , "name" : "Buttermilk Lemon" , "price":190, "image" : "foto-12.jpg" },
  { "id" : 13 , "name" : "HAND BALSAM" , "price":190, "image" : "foto-13.jpg" },
  { "id" : 14 , "name" : "HAND CREME  " , "price":190, "image" : "foto-14.jpg" },
  { "id" : 15 , "name" : "Olive HAND CREME  " , "price":190, "image" : "foto-15.jpg" },
  { "id" : 16 , "name" : "Donto dent" , "price":120, "image" : "foto-16.jpg" },
  { "id" : 17 , "name" : "VITAMIN C " , "price":130, "image" : "foto-17.jpg" },
  { "id" : 18 , "name" : "Scrub & Care" , "price":130, "image" : "foto-18.jpg" },
  { "id" : 19 , "name" : "DEOCREME " , "price":280, "image" : "foto-19.jpg" },
  { "id" : 20 , "name" : "Sensitive DEOCREME " , "price":280, "image" : "foto-20.jpg" },
  { "id" : 21 , "name" : "كبسولات العناية بالبشرة " , "price":190, "image" : "foto-21.jpg" },
  { "id" : 22 , "name" : "VITAMIN C KONZENTRAT" , "price":190, "image" : "foto-22.jpg" },
  { "id" : 23 , "name" : "HYALURON KONZENTRAT" , "price":190, "image" : "foto-23.jpg" },
  { "id" : 24 , "name" : "Q10  ANTI -FALTEN" , "price":190, "image" : "foto-24.jpg" },
  { "id" : 25 , "name" : "Cherry love Hydrogel " , "price":130, "image" : "foto-25.jpg" },
  { "id" : 26 , "name" : "TROPICAL LOVE" , "price":130, "image" : "foto-26.jpg" },
  { "id" : 27 , "name" : "TROPICAL LOVE" , "price":130, "image" : "foto-27.jpg" },
  { "id" : 28 , "name" : "Hydrogel🌸 AUGENPADS" , "price":130, "image" : "foto-28.jpg" },
  { "id" : 29 , "name" : "Hydrogel 🌸 AUGENPADS " , "price":130, "image" : "foto-29.jpg" },
  { "id" : 30 , "name" : "Hydrogel🔥 AUGENPADS  " , "price":130, "image" : "foto-30.jpg" },
  { "id" : 31 , "name" : "Hydrogel AUGENPADS " , "price":130, "image" : "foto-31.jpg" },
  { "id" : 32 , "name" : "Hydrogel🌸 AUGENPADS " , "price":130, "image" : "foto-32.jpg" },
  { "id" : 33 , "name" : "EYE PAD MASK" , "price":130, "image" : "foto-33.jpg" },
  { "id" : 34 , "name" : "PARFUM. DEODORANT 0%" , "price":190, "image" : "foto-34.jpg" },
  { "id" : 35 , "name" : "PARFUM . DEODORANT 0% " , "price":190, "image" : "foto-35.jpg" },
  { "id" : 36 , "name" : "PARFUM . DEODORANT 0%" , "price":190, "image" : "foto-36.jpg" },
  { "id" : 37 , "name" : "PARFUM . DEODORANT 0%" , "price":190, "image" : "foto-37.jpg" },
  { "id" : 38 , "name" : "ANTI - TRANSPIRANT" , "price":190, "image" : "foto-38.jpg" },
  { "id" : 39 , "name" : "Soft FIOWer 🌸DEODORANT " , "price":190, "image" : "foto-39.jpg" },

] 