
export const allProducts = [

  { "id": 1, "name": "Lovely pistachio Maske", "price": 80, "image": "foto-1.jpg" },
  { "id": 2, "name": "Vitamin C Maske", "price": 80, "image": "foto-2.jpg" },
  { "id": 3, "name": "ALOE  VERA  MASKE", "price": 80, "image": "foto-3.jpg" },
  { "id": 4, "name": "HoNIG MASKE", "price": 80, "image": "foto-4.jpg" },
  { "id": 5, "name": "TOTES MEER MASKE", "price": 80, "image": "foto-5.jpg" },
  { "id": 6, "name": "GLOW PEEL", "price": 80, "image": "foto-6.jpg" },
  { "id": 7, "name": "RETINOL MASKE", "price": 80, "image": "foto-7.jpg" },
  { "id": 8, "name": "FALTEN MASKE", "price": 80, "image": "foto-8.jpg" },
  { "id": 9, "name": "Creme - ölHANDLOTION", "price": 190, "image": "foto-9.jpg" },
  { "id": 10, "name": "GLamoIous Moment", "price": 190, "image": "foto-10.jpg" },
  { "id": 11, "name": "Schnell  einziehende", "price": 190, "image": "foto-11.jpg" },
  { "id": 12, "name": "Buttermilk Lemon", "price": 190, "image": "foto-12.jpg" },
  { "id": 13, "name": "HAND BALSAM", "price": 190, "image": "foto-13.jpg" },
  { "id": 14, "name": "HAND CREME", "price": 190, "image": "foto-14.jpg" },
  { "id": 15, "name": "Olive HAND CREME", "price": 190, "image": "foto-15.jpg" },
  { "id": 16, "name": "Donto dent", "price": 120, "image": "foto-16.jpg" },
  { "id": 17, "name": "VITAMIN C", "price": 130, "image": "foto-17.jpg" },
  { "id": 18, "name": "Scrub & Care", "price": 130, "image": "foto-18.jpg" },
  { "id": 19, "name": "DEOCREME", "price": 280, "image": "foto-19.jpg" },
  { "id": 20, "name": "Sensitive DEOCREME", "price": 280, "image": "foto-20.jpg" },
  { "id": 21, "name": "كبسولات العناية بالبشرة", "price": 190, "image": "foto-21.jpg" },
  { "id": 22, "name": "VITAMIN C KONZENTRAT", "price": 190, "image": "foto-22.jpg" },
  { "id": 23, "name": "HYALURON KONZENTRAT", "price": 190, "image": "foto-23.jpg" },
  { "id": 24, "name": "Q10  ANTI -FALTEN", "price": 190, "image": "foto-24.jpg" },
  { "id": 25, "name": "Cherry love Hydrogel", "price": 130, "image": "foto-25.jpg" },
  { "id": 26, "name": "TROPICAL LOVE", "price": 130, "image": "foto-26.jpg" },
  { "id": 27, "name": "TROPICAL LOVE", "price": 130, "image": "foto-27.jpg" },
  { "id": 28, "name": "Hydrogel🌸 AUGENPADS", "price": 130, "image": "foto-28.jpg" },
  { "id": 29, "name": "Hydrogel 🌸 AUGENPADS", "price": 130, "image": "foto-29.jpg" },
  { "id": 30, "name": "Hydrogel🔥 AUGENPADS", "price": 130, "image": "foto-30.jpg" },
  
  { "id": 31, "name": "Hydrogel AUGENPADS", "price": 130, "image": "foto-31.jpg" },
  { "id": 32, "name": "Hydrogel🌸 AUGENPADS", "price": 130, "image": "foto-32.jpg" },
  { "id": 33, "name": "EYE PAD MASK", "price": 130, "image": "foto-33.jpg" },
  { "id": 34, "name": "PARFUM. DEODORANT 0%", "price": 190, "image": "foto-34.jpg" },
  { "id": 35, "name": "PARFUM . DEODORANT 0%", "price": 190, "image": "foto-35.jpg" },
  { "id": 36, "name": "PARFUM . DEODORANT 0%", "price": 190, "image": "foto-36.jpg" },
  { "id": 37, "name": "PARFUM . DEODORANT 0%", "price": 190, "image": "foto-37.jpg" },
  { "id": 38, "name": "ANTI - TRANSPIRANT", "price": 190, "image": "foto-38.jpg" },
  { "id": 39, "name": "Soft FIOWer 🌸DEODORANT", "price": 190, "image": "foto-39.jpg" },
  { "id": 40, "name": "Sensitive DEODORANT 0%", "price": 190, "image": "foto-40.jpg" },
  { "id": 41, "name": "Vanille & Kokos", "price": 190, "image": "foto-41.jpg" },
  { "id": 42, "name": "SWeet Sunshine 0%", "price": 190, "image": "foto-42.jpg" },
  { "id": 43, "name": "EXtra Dry", "price": 190, "image": "foto-43.jpg" },
  { "id": 44, "name": "Sensitive DEODORANT 0%", "price": 190, "image": "foto-44.jpg" },
  { "id": 45, "name": "5 in1 Protection", "price": 190, "image": "foto-45.jpg" },
  { "id": 46, "name": "Extra Dry", "price": 180, "image": "foto-46.jpg" },
  { "id": 47, "name": "Soft 🌸 Flower", "price": 180, "image": "foto-47.jpg" },
  { "id": 48, "name": "Sweet  Sunshine", "price": 150, "image": "foto-48.jpg" },
  { "id": 49, "name": "LIPPEN PFLEGE", "price": 150, "image": "foto-49.jpg" },
  { "id": 50, "name": "LIPPEN PFLEGE MEN", "price": 150, "image": "foto-50.jpg" },
  { "id": 51, "name": "LIPPEN PFLEGE 🌸ROSé", "price": 150, "image": "foto-51.jpg" },
  { "id": 52, "name": "LIPPEN PFLEGE", "price": 150, "image": "foto-52.jpg" },
  { "id": 53, "name": "LIPPEN PFLEGE", "price": 150, "image": "foto-53.jpg" },
  { "id": 54, "name": "LIPPEN PFLEGE", "price": 150, "image": "foto-54.jpg" },
  { "id": 55, "name": "LIPPEN PFLEGE", "price": 150, "image": "foto-55.jpg" },
  { "id": 56, "name": "LIPPEN PFLEGE", "price": 150, "image": "foto-56.jpg" },
  { "id": 57, "name": "LIPPEN PFLEGE", "price": 150, "image": "foto-57.jpg" },
  { "id": 58, "name": "LIPPEN PFLEGE", "price": 150, "image": "foto-58.jpg" },
  { "id": 59, "name": "LIPPEN PFLEGE", "price": 180, "image": "foto-59.jpg" },
  { "id": 60, "name": "TUCHMASKE", "price": 130, "image": "foto-60.jpg" },
  { "id": 61, "name": "TUCHMASKE", "price": 130, "image": "foto-61.jpg" },
  { "id": 62, "name": "TUCHMASKE", "price": 130, "image": "foto-62.jpg" },
  { "id": 63, "name": "TUCHMASKE", "price": 130, "image": "foto-63.jpg" },
  { "id": 64, "name": "TUCHMASKE", "price": 130, "image": "foto-64.jpg" },
  { "id": 65, "name": "TUCHMASKE", "price": 130, "image": "foto-65.jpg" },
  { "id": 66, "name": "Vitamin  B12", "price": 180, "image": "foto-66.jpg" },
  { "id": 67, "name": "Calcium", "price": 180, "image": "foto-67.jpg" },
  { "id": 68, "name": "MuIti - Mineral", "price": 180, "image": "foto-68.jpg" },
  { "id": 69, "name": "Vitamin C", "price": 180, "image": "foto-69.jpg" },
  { "id": 70, "name": "Eisen + Vitamin C ", "price": 180, "image": "foto-70.jpg" },
  { "id": 71, "name": "Multivitamin", "price": 180, "image": "foto-71.jpg" },
  { "id": 72, "name": "Vitamin C ", "price": 180, "image": "foto-72.jpg" },
  { "id": 73, "name": "Magnesium", "price": 180, "image": "foto-73.jpg" },
  { "id": 74, "name": "Magnesium", "price": 180, "image": "foto-74.jpg" },
  { "id": 75, "name": "A-Z Komplett Depot", "price": 450, "image": "foto-75.jpg" },
  { "id": 76, "name": "Omega - 3", "price": 450, "image": "foto-76.jpg" },
  { "id": 77, "name": "Fett Blocker ", "price": 450, "image": "foto-77.jpg" },
  { "id": 78, "name": "Haut + Haare +Nägel", "price": 450, "image": "foto-78.jpg" },
  { "id": 79, "name": "Wärmepflaster", "price": 300, "image": "foto-79.jpg" },
  { "id": 80, "name": "SüBstoff", "price": 190, "image": "foto-80.jpg" },
  { "id": 81, "name": "KLINGEN  EINWEG  RASIERER", "price": 260, "image": "foto-82.jpg" },
  { "id": 82, "name": "KLINGEN", "price": 260, "image": "foto-83.jpg" },
  { "id": 83, "name": "hautrein ANTI - PICKEL", "price": 250, "image": "foto-84.jpg" },
  { "id": 84, "name": "Anti - Pimple Stars", "price": 260, "image": "foto-85.jpg" }

];
